apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sync-patrol
  description: Check sync between BFF and Core Services
  annotations:
    github.com/project-slug: Gaardsholt/test
    circleci.com/project-slug: github/Gaardsholt/barcoder
spec:
  type: service
  lifecycle: experimental
  owner: "@BESTSELLER/sales-and-invoicing"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sync-patrol-api
  description: sync-patrol api
spec:
  type: openapi
  lifecycle: production
  owner: "@BESTSELLER/sales-and-invoicing"
  system: sync-patrol
  definition:
    $text: https://github.com/BESTSELLER/sync-patrol/blob/master/docs/swagger.yaml #After api has been deployed change this to "https://sync-patrol.k8s.bestcorp.net"




